##################################################
# PROGUARD CONFIG – FINAL (NO INPUT / OUTPUT)
##################################################

# ===== JAVA RUNTIME =====
-libraryjars <java.home>/jmods/java.base.jmod

# ===== SPRING / JAKARTA =====
-keep class org.springframework.** { *; }
-keep class jakarta.** { *; }
-keep class javax.** { *; }

# ===== MAIN CLASS =====
-keep class com.example.hospitalmanagements.HospitalmanagementsApplication {
    public static void main(java.lang.String[]);
}

# ===== CONTROLLERS =====
-keep class com.example.hospitalmanagements.controller.** { *; }

# ===== ENTITIES =====
-keep class com.example.hospitalmanagements.entity.** { *; }

# ===== LICENSE =====
-keep class com.example.hospitalmanagements.license.** { *; }

# ===== OBFUSCATION =====
-dontwarn
-ignorewarnings
-dontoptimize
-dontpreverify
-overloadaggressively
-repackageclasses ''
-allowaccessmodification

# (اختياري للتشخيص)
# -printmapping target/proguard_map.txt
# -printseeds target/proguard_seed.txt
